AlumnosCRUD/AlumnosCRUD/Controllers/AlumnoController.cs
using AlumnosCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlumnosCRUD.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        public ActionResult Listado()
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    List<Alumno> lista = db.Alumno.ToList();
                    return View(lista);
                }

            }
            catch (Exception ex)
            {
                throw;
            }

        }
        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(Alumno a)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new AlumnosContext())
                {
                    db.Alumno.Add(a);
                    db.SaveChanges();
                    return RedirectToAction("Listado");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al crear el registro", ex);
                return View();
            }

        }

        public ActionResult Editar(int id)
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    Alumno alu = db.Alumno.Find(id);
                    return View(alu);
                }
            }
            catch (Exception ex)
            {
                throw;
            }



        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Alumno a)
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    Alumno al = db.Alumno.Find(a.Id);
                    al.NombreAlumno = a.NombreAlumno;
                    al.ApellidoAlumno = a.ApellidoAlumno;
                    al.Edad = a.Edad;
                    al.Sexo = a.Sexo;
                    al.FechaIngreso = a.FechaIngreso;

                    db.SaveChanges();

                    return RedirectToAction("Listado");
                }
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        public ActionResult Detalles(int id)
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    Alumno alu = db.Alumno.Find(id);
                    return View(alu);
                }
            }
            catch (Exception ex)
            {
                throw;
            }


        }

        public ActionResult Borrar(int id)
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    Alumno alu = db.Alumno.Find(id);
                    db.Alumno.Remove(alu);
                    db.SaveChanges();
                    return RedirectToAction("Listado");
                }
            }
            catch (Exception ex)
            {
                throw;
            }


        }
    }
}

AlumnosCRUD/AlumnosCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Alumnos", "Listado", "Alumno")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>